OpenTokSamples/app/build.gradle
OpenTokSamples/app/src/main/AndroidManifest.xml
OpenTokSamples/app/src/main/java/com/opentok/android/demo/audio/CustomAudioDevice.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/config/OpenTokConfig.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/multiparty/MySession.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/multiparty/MySubscriber.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/AudioDeviceActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/BuildConfig.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/EmulatorActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/HelloWorldActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/MultipartyActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/OpenTokSamples.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/R.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/ScreenSharingActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/UIActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/VideoCapturerActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/VideoRendererActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/VoiceOnlyActivity.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/test/BuildConfig.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/screensharing/ScreensharingCapturer.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/services/ClearNotificationService.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/ui/AudioLevelView.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/ui/MeterView.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/ui/fragments/PublisherControlFragment.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/ui/fragments/PublisherStatusFragment.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/ui/fragments/SubscriberControlFragment.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/ui/fragments/SubscriberQualityFragment.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/video/CustomEmulatorVideoCapturer.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/video/CustomVideoCapturer.java
OpenTokSamples/app/src/main/java/com/opentok/android/demo/video/CustomVideoRenderer.java

Changed jni libs dir to `jniLibs`
Removed VIDEO_FILL on Screensharing example.
Fixed package name in AndroidManifest

Reformatting (Using Android Studio code style)

---

OpenTokSamples/app/src/main/res/layout-land/layout_fragment_pub_status.xml
OpenTokSamples/app/src/main/res/layout-port/layout_fragment_pub_status.xml
OpenTokSamples/app/src/main/res/layout/voice_only_layout.xml

Fixed OPENTOK-26801 Now build can be built from command line interface with ./gradlew assembleRelease

Fixed OPENTOK-26801

---

OpenTokSamples/app/build.gradle
OpenTokSamples/app/src/main/AndroidManifest.xml
OpenTokSamples/app/src/main/java/com/opentok/android/demo/opentoksamples/OpenTokSamples.java
OpenTokSamples/app/src/main/res/values/strings.xml

OPENTOK-28299. Update Android Sample Applications to support new Android Permission System, r=rpc

---

OpenTokSamples/app/build.gradle
OpenTokSamples/app/jniLibs/README.md
OpenTokSamples/build.gradle
README.md

Please don't merge this until the release has been made. This makes the samples use maven to fetch opentok-android-sdk.

Added support for maven

---

OpenTokSamples/app/src/main/AndroidManifest.xml
README.md

(The SDK adds these automatically.)

Removing unneeded permissions from the manifest.

---

OpenTokSamples/app/build.gradle
OpenTokSamples/build.gradle
OpenTokSamples/gradle/wrapper/gradle-wrapper.properties

This is to be merged after the 2.9 release.

Updated to support android-sdk-2.9.0

---

OpenTokSamples/2.Custom-Video-Driver/README.md
OpenTokSamples/2.Custom-Video-Driver/src/main/java/com/opentok/android/samples/custom_video_driver/InvertedColorsVideoRenderer.java
OpenTokSamples/2.Custom-Video-Driver/src/main/java/com/opentok/android/samples/custom_video_driver/MainActivity.java

@marinaserranomontes @jaoo can you review this please?

OPENTOK-31496: Make clear we are inverting colors on purpose. r=marina,jaoo

---

Custom-Audio-Driver/README.md
Custom-Video-Driver/README.md
FrameMetadata/README.md
Live-Photo-Capture/README.md
Multiparty-ConstraintLayout/README.md
Screen-Sharing/README.md
Simple-Multiparty/README.md

This PR replaces all references of "Project 1" with "Basic-Video-Chat", our "Hello World" app.

OPENTOK-41606: Replace references of "Project 1" with "Basic-Video-Chat"

---

Simple-Multiparty/README.md

The README changes code snippets that were removed from the reference code during refactoring.  This PR updates the README with the code currently in use.  Also, some light editing was done as well.

OPENTOK-41606: Update README with code changes

---

Custom-Audio-Driver/app/build.gradle
Custom-Audio-Driver/app/src/main/java/com/tokbox/android/tutorials/custom_audio_driver/CustomAudioDevice.java

Class method call 
```
BaseAudioDevice.publisherError(e)
```
was removed and changed 
```
throw new RuntimeException(e.getMessage())
```
till the BaseAudioDevice class is fixed
Also added a package name for Junit test in app gradle

BaseAudioDevice missing a "public"  for package access

---

Screen-Sharing/README.md
Screen-Sharing/app/src/main/java/com/tokbox/android/tutorials/screen_sharing/MainActivity.java

Fixes bug where sample app didn't load tokbox.com and showed an error message intead
- Clone this branch and build the sample app
- Run it
- Notice that tokbox.com site loads again
Resolves [OPENTOK-42100](https://tokbox.atlassian.net/browse/OPENTOK-42100)

OPENTOK-42100: Fix bug where tokbox site didn't load

---

Archiving/app/src/main/res/layout/activity_main.xml

Remove old reference to `support` layout

Fix layout Archiving project

---

Archiving/app/src/main/java/com/tokbox/sample/archiving/MainActivity.java
Archiving/app/src/main/java/com/tokbox/sample/archiving/network/APIService.java
Basic-Video-Chat/app/src/main/java/com/tokbox/sample/basicvideochat/MainActivity.java

- Change publisher initialization logic
- Fix stop recording

Change publisher initialisation logic and fix stop recording request

---

ARCore-Integration/app/src/main/java/com/tokbox/sample/arcoreintegration/MainActivity.java
ARCore-Integration/app/src/main/java/com/tokbox/sample/arcoreintegration/OpenTokConfig.java
Archiving/app/src/main/java/com/tokbox/sample/archiving/MainActivity.java
Archiving/app/src/main/java/com/tokbox/sample/archiving/OpenTokConfig.java
Basic-Video-Capturer-Camera-2/app/src/main/java/com/tokbox/sample/basicvideocapturercamera2/MainActivity.java
Basic-Video-Capturer-Camera-2/app/src/main/java/com/tokbox/sample/basicvideocapturercamera2/OpenTokConfig.java
Basic-Video-Capturer/app/src/main/java/com/tokbox/sample/basicvideocapturer/MainActivity.java
Basic-Video-Capturer/app/src/main/java/com/tokbox/sample/basicvideocapturer/OpenTokConfig.java
Basic-Video-Chat/app/src/main/java/com/tokbox/sample/basicvideochat/MainActivity.java
Basic-Video-Chat/app/src/main/java/com/tokbox/sample/basicvideochat/OpenTokConfig.java
Basic-Video-Renderer/app/src/main/java/com/tokbox/sample/basicvideorenderer/MainActivity.java
Basic-Video-Renderer/app/src/main/java/com/tokbox/sample/basicvideorenderer/OpenTokConfig.java
Custom-Audio-Driver/app/src/main/java/com/tokbox/sample/customaudiodriver/MainActivity.java
Custom-Audio-Driver/app/src/main/java/com/tokbox/sample/customaudiodriver/OpenTokConfig.java
Custom-Video-Driver/app/src/main/java/com/tokbox/sample/customvideodriver/MainActivity.java
Custom-Video-Driver/app/src/main/java/com/tokbox/sample/customvideodriver/OpenTokConfig.java
Frame-Metadata/app/src/main/java/com/tokbox/sample/framemetadata/MainActivity.java
Frame-Metadata/app/src/main/java/com/tokbox/sample/framemetadata/OpenTokConfig.java
Live-Photo-Capture/app/src/main/java/com/tokbox/android/sample/livephotocapture/MainActivity.java
Live-Photo-Capture/app/src/main/java/com/tokbox/android/sample/livephotocapture/OpenTokConfig.java
Multiparty-Constraint-Layout/app/src/main/java/com/tokbox/sample/multipartyconstraintlayout/MainActivity.java
Multiparty-Constraint-Layout/app/src/main/java/com/tokbox/sample/multipartyconstraintlayout/OpenTokConfig.java
Picture-In-Picture/app/src/main/java/com/tokbox/sample/pictureinpicture/MainActivity.java
Picture-In-Picture/app/src/main/java/com/tokbox/sample/pictureinpicture/OpenTokConfig.java
Screen-Sharing/app/src/main/java/com/tokbox/sample/screensharing/MainActivity.java
Screen-Sharing/app/src/main/java/com/tokbox/sample/screensharing/OpenTokConfig.java
Signaling/app/src/main/java/com/tokbox/sample/signaling/MainActivity.java
Signaling/app/src/main/java/com/tokbox/sample/signaling/OpenTokConfig.java
Simple-Multiparty/app/src/main/java/com/tokbox/sample/simplemultiparty/MainActivity.java
Simple-Multiparty/app/src/main/java/com/tokbox/sample/simplemultiparty/OpenTokConfig.java

Verify credentials in each project on the app launch

devx-5169 Add OpenTokConfig verification

---

ARCore-Integration/app/src/main/java/com/tokbox/sample/arcoreintegration/MainActivity.java
Archiving/app/src/main/java/com/tokbox/sample/archiving/MainActivity.java
Basic-Video-Capturer-Camera-2/app/src/main/java/com/tokbox/sample/basicvideocapturercamera2/MainActivity.java
Basic-Video-Capturer/app/src/main/java/com/tokbox/sample/basicvideocapturer/MainActivity.java
Basic-Video-Chat/app/src/main/java/com/tokbox/sample/basicvideochat/MainActivity.java
Basic-Video-Renderer/app/src/main/java/com/tokbox/sample/basicvideorenderer/MainActivity.java
Custom-Audio-Driver/app/src/main/java/com/tokbox/sample/customaudiodriver/MainActivity.java
Custom-Video-Driver/app/src/main/java/com/tokbox/sample/customvideodriver/MainActivity.java
Frame-Metadata/app/src/main/java/com/tokbox/sample/framemetadata/MainActivity.java
Live-Photo-Capture/app/src/main/java/com/tokbox/android/sample/livephotocapture/MainActivity.java
Multiparty-Constraint-Layout/app/src/main/java/com/tokbox/sample/multipartyconstraintlayout/MainActivity.java
Picture-In-Picture/app/src/main/java/com/tokbox/sample/pictureinpicture/MainActivity.java
Screen-Sharing/app/src/main/java/com/tokbox/sample/screensharing/MainActivity.java
Signaling/app/src/main/java/com/tokbox/sample/signaling/MainActivity.java
Simple-Multiparty/app/src/main/java/com/tokbox/sample/simplemultiparty/MainActivity.java

- Remove Android lifecycle logs
- Unify logs across project

devx-5173 Unify logging

---

README.md
check-consistancy.kts

Kepp top-level readme more concise, so it is easier to review project list.

Update readme format

---

Live-Photo-Capture/README.md
Live-Photo-Capture/app/src/main/java/com/tokbox/sample/livephotocapture/MainActivity.java
Live-Photo-Capture/app/src/main/java/com/tokbox/sample/livephotocapture/ScreenshotVideoRenderer.java

- Rename class to `ScreenshotVideoRenderer`
- store `saveScreenshot` property in `MyRenderer`

Simplify Live Photo Capture

---

.test/build.gradle.kts
ARCore-Integration/build.gradle
Advanced-Audio-Driver/build.gradle
Archiving/build.gradle
Basic-Audio-Driver/build.gradle
Basic-Video-Capturer-Camera-2/build.gradle
Basic-Video-Capturer/build.gradle
Basic-Video-Chat/build.gradle
Basic-Video-Driver/build.gradle
Basic-Video-Renderer/build.gradle
Frame-Metadata/build.gradle
Live-Photo-Capture/build.gradle
Multiparty-Constraint-Layout/build.gradle
Picture-In-Picture/build.gradle
Screen-Sharing/build.gradle
Signaling/build.gradle
Simple-Multiparty/build.gradle

Remove all of the JCeter references

Replace Android samples bintray links with Maven Central links Part 2

---

Phone-Call-Detection/README.md
Phone-Call-Detection/app/src/main/java/com/tokbox/sample/phonecalldetection/MainActivity.java

Disable audio/video for the phone call duration.

Update phone detection sample

---

commons.gradle

Updated the ARCore package to fix reported issue under DEVX-6232

Updated ARCore to fix metadata bug

---

Phone-Call-Detection-Kotlin/app/build.gradle
commons.gradle

Update Android sample apps to the latest version
https://jira.vonage.com/browse/OPENTOK-48551

OPENTOK-48551: Update all Android samples to latest version

---

Basic-Audio-Driver-Java/app/build.gradle
Basic-Audio-Driver-Kotlin/app/build.gradle
Phone-Call-Detection-Kotlin/app/build.gradle

Increase minSDK version from 19 to 21.

Increase minSDK version from 19 to 21

---

commons.gradle

Update android sdk to 2.27.0 for all samples

Update Android sdk to 2.27.0

---

Basic-Video-Capturer-Camera-2-Java/app/src/main/java/com/tokbox/sample/basicvideocapturercamera2/MirrorVideoCapturer.java

Update Capturer including recent fixes in default capturer

VIDCS-2430: Fix crash when publishing/unpublishing quickly

---

commons.gradle

What is this PR doing?
Bump up version string of android samples to 2.29.2.

chetan/VIDCS-3574: Bump up version string of android samples to 2.29.2
